name: Manifest Sync

on:
  workflow_dispatch:
    inputs:
      GameType:
        description: 'Game mode to update manifest for'
        required: true
        default: 'MoM'
        type: choice
        options:
          - D2E
          - MoM

jobs:
  sync-manifest:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set GameType from workflow_dispatch
        if: github.event_name == 'workflow_dispatch'
        run: echo "GameType=${{ github.event.inputs.GameType }}" >> $GITHUB_ENV

      - name: Fetch manifest.ini
        id: fetch_manifest
        run: |
          if [[ "$GameType" == "D2E" ]]; then
            curl -s -H "Authorization: token $GITHUB_TOKEN" \
              https://api.github.com/repos/NPBruce/valkyrie-store/contents/D2E/manifest.ini \
              | jq -r .content | base64 -d > manifest.ini
          else
            curl -s -H "Authorization: token $GITHUB_TOKEN" \
              https://api.github.com/repos/NPBruce/valkyrie-store/contents/MoM/manifest.ini \
              | jq -r .content | base64 -d > manifest.ini
          fi

      - name: Parse manifest and fetch scenario data
        id: parse_and_fetch
        run: |
          pip install requests configparser
          python .github/scripts/manifest_sync.py "$GameType"

      - name: Commit and push manifestDownload.ini for D2E
        if: env.GameType == 'D2E'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update manifestDownload.ini for ${{ env.GameType }}"
          file_pattern: |
            D2E/manifestDownload.ini

      - name: Commit and push manifestDownload.ini for MoM
        if: env.GameType == 'MoM'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update manifestDownload.ini for ${{ env.GameType }}"
          file_pattern: |
            MoM/manifestDownload.ini